# Generated by Django 4.2.5 on 2023-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldstaffinformation',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fieldstaffinformation',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
